name: chat_x
description: "A new Flutter project."

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.3.3 <4.0.0"

dependencies:
  auto_route: ^8.1.0
  bloc: ^8.1.4
  cupertino_icons: ^1.0.6
  dartz: ^0.10.1
  device_preview: ^1.1.0
  dio: ^5.4.3+1
  envied: ^0.5.4+1
  equatable: ^2.0.5
  fancy_shimmer_image: ^2.0.3
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.5
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  freezed: ^2.5.2
  freezed_annotation: ^2.4.1
  get_it: ^7.7.0
  injectable: ^2.4.1
  intl: ^0.18.1
  json_annotation: ^4.8.1
  json_serializable: ^6.7.1
  package_info_plus: ^7.0.0
  pretty_dio_logger: ^1.3.1
  shimmer: ^3.0.0

dev_dependencies:
  auto_route_generator: ^8.0.0
  build_runner: ^2.4.9
  envied_generator: ^0.5.4+1
  flutter_gen_runner: ^5.4.0
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.6.1

flutter_gen:
  output: lib/generate/gen

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Rubik
      fonts:
        - asset: assets/fonts/rubik/Rubik-Light.ttf
          weight: 300
        - asset: assets/fonts/rubik/Rubik-Regular.ttf
          weight: 400
        - asset: assets/fonts/rubik/Rubik-Medium.ttf
          weight: 500
        - asset: assets/fonts/rubik/Rubik-Bold.ttf
          weight: 700
